TestCaseName:
  - 'Login success'
  - 'Login failed - Password incorrect'
  - 'Login failed - Username not found incorrect'

Obective :
  - 'verify that users can login successfully when input a correct username and password.'
  - 'verify that users can login unsuccessfully when they input a correct username but wrong password.'
  - 'verify that users can login unsuccessfully when they input a username that did not exist.'

TestStep:
  - |
    1. Open browser and go to http://theinternet.herokuapp.com/login.  
    2. Input username tomsmith and password  SuperSecretPassword!.  
    3. Click the Logout button.

  - |
    1. Open browser and go to http://theinternet.herokuapp.com/login.  
    2. Input username tomsmith and password Password!.

  - |
    1. Open browser and go to http://theinternet.herokuapp.com/login.  
    2. Input username tomholland and password Password!.

ExpectedResult:
  - |
    1. Login page is shown. 
    2. Login success and message You logged into a secure area! is shown.  
    3. Go back to the Login page and the message  You logged out of the secure area! is shown.

  - |
    1. Login page is shown. 
    2. Login failed and the message Your password is invalid! is shown.

  - |
    1. Login page is shown.  
    2. Login failed and the message Your username is invalid! is shown.

Data :
  -  
    userName : 'tomsmith'
    passWord : 'SuperSecretPassword!'

  -  
    userName : 'tomsmith'
    passWord : 'Password!'
    
  -  
    userName : 'tomholland'
    passWord : 'Password!'